//! TPM Configuration and Feature Detection
//! Generated by tpm_migration.sh

use serde::{Deserialize, Serialize};

/// TPM type enumeration
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum TpmType {
    /// Real hardware TPM 2.0
    Hardware,
    /// Software TPM simulator
    Software,
    /// No TPM available
    None,
}

/// TPM configuration loaded from config/tpm/tpm_config.yaml
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TpmConfig {
    pub tpm_type: TpmType,
    pub available: bool,
    pub pcr_sape: u8,
    pub pcr_fate: u8,
    pub pcr_spine: u8,
    pub pcr_sovereign: u8,
    pub fallback_enabled: bool,
    pub warn_on_fallback: bool,
}

impl Default for TpmConfig {
    fn default() -> Self {
        Self {
            tpm_type: TpmType::Software,
            available: false,
            pcr_sape: 12,
            pcr_fate: 13,
            pcr_spine: 14,
            pcr_sovereign: 15,
            fallback_enabled: true,
            warn_on_fallback: true,
        }
    }
}

impl TpmConfig {
    /// Load configuration from file
    pub fn load() -> Result<Self, Box<dyn std::error::Error>> {
        let config_path = "config/tpm/tpm_config.yaml";
        if std::path::Path::new(config_path).exists() {
            let yaml = std::fs::read_to_string(config_path)?;
            // Parse and return
            Ok(Self::default()) // TODO: Parse YAML
        } else {
            Ok(Self::default())
        }
    }
    
    /// Check if real hardware TPM is available
    pub fn is_hardware(&self) -> bool {
        self.tpm_type == TpmType::Hardware && self.available
    }
}
