#!/bin/bash
# SAPE v1.∞ EXECUTION: TPM HARDWARE MIGRATION
# Part of 72-Hour Critical Gap Remediation Sprint
set -e

echo "🔧 BIZRA HARDWARE TRUST: TPM MIGRATION PROTOCOL..."
echo "========================================================================"

GIT_ROOT=$(git rev-parse --show-toplevel 2>/dev/null || echo ".")
cd "$GIT_ROOT"

# 1. Detect TPM availability
echo ""
echo "📋 Phase 1: Detecting TPM hardware..."

TPM_AVAILABLE=false
TPM_TYPE="none"

# Check for TPM 2.0
if [ -c /dev/tpm0 ] || [ -c /dev/tpmrm0 ]; then
    echo "  ✓ TPM 2.0 device detected (/dev/tpm0 or /dev/tpmrm0)"
    TPM_AVAILABLE=true
    TPM_TYPE="hardware"
elif command -v tpm2_getcap &>/dev/null; then
    echo "  ✓ TPM 2.0 tools available"
    if tpm2_getcap properties-fixed 2>/dev/null | grep -q "TPM2_PT_FAMILY_INDICATOR"; then
        TPM_AVAILABLE=true
        TPM_TYPE="hardware"
        echo "  ✓ TPM 2.0 hardware confirmed"
    else
        echo "  ⚠ TPM 2.0 tools present but hardware not accessible"
    fi
else
    echo "  ⚠ TPM 2.0 not detected"
fi

# Check for software TPM simulator
if command -v swtpm &>/dev/null; then
    echo "  ℹ Software TPM (swtpm) available as fallback"
    if [ "$TPM_TYPE" = "none" ]; then
        TPM_TYPE="software"
    fi
fi

# 2. Create TPM configuration
echo ""
echo "📋 Phase 2: Creating TPM configuration..."

mkdir -p config/tpm

cat > config/tpm/tpm_config.yaml << EOF
# BIZRA TPM Configuration
# Generated: $(date -u +"%Y-%m-%dT%H:%M:%SZ")

tpm:
  type: "${TPM_TYPE}"
  available: ${TPM_AVAILABLE}
  
  # PCR slots used by BIZRA
  pcr_slots:
    sape: 12       # SAPE scoring engine measurements
    fate: 13       # FATE verification measurements
    spine: 14      # Polyglot spine measurements
    sovereign: 15  # Sovereign kernel measurements
  
  # Attestation configuration
  attestation:
    key_algorithm: "RSA-2048"
    hash_algorithm: "SHA-256"
    signing_scheme: "RSASSA-PKCS1-v1_5"
  
  # Fallback behavior
  fallback:
    enabled: true
    mode: "software"  # Use software TPM if hardware unavailable
    warn_on_fallback: true
EOF

echo "  ✓ Configuration saved to: config/tpm/tpm_config.yaml"

# 3. Generate TPM wrapper module
echo ""
echo "📋 Phase 3: Generating TPM wrapper module..."

mkdir -p src/tpm

cat > src/tpm/config.rs << 'EOF'
//! TPM Configuration and Feature Detection
//! Generated by tpm_migration.sh

use serde::{Deserialize, Serialize};

/// TPM type enumeration
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum TpmType {
    /// Real hardware TPM 2.0
    Hardware,
    /// Software TPM simulator
    Software,
    /// No TPM available
    None,
}

/// TPM configuration loaded from config/tpm/tpm_config.yaml
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TpmConfig {
    pub tpm_type: TpmType,
    pub available: bool,
    pub pcr_sape: u8,
    pub pcr_fate: u8,
    pub pcr_spine: u8,
    pub pcr_sovereign: u8,
    pub fallback_enabled: bool,
    pub warn_on_fallback: bool,
}

impl Default for TpmConfig {
    fn default() -> Self {
        Self {
            tpm_type: TpmType::Software,
            available: false,
            pcr_sape: 12,
            pcr_fate: 13,
            pcr_spine: 14,
            pcr_sovereign: 15,
            fallback_enabled: true,
            warn_on_fallback: true,
        }
    }
}

impl TpmConfig {
    /// Load configuration from file
    pub fn load() -> Result<Self, Box<dyn std::error::Error>> {
        let config_path = "config/tpm/tpm_config.yaml";
        if std::path::Path::new(config_path).exists() {
            let yaml = std::fs::read_to_string(config_path)?;
            // Parse and return
            Ok(Self::default()) // TODO: Parse YAML
        } else {
            Ok(Self::default())
        }
    }
    
    /// Check if real hardware TPM is available
    pub fn is_hardware(&self) -> bool {
        self.tpm_type == TpmType::Hardware && self.available
    }
}
EOF

echo "  ✓ Created src/tpm/config.rs"

# 4. Update Cargo.toml with TPM features
echo ""
echo "📋 Phase 4: Updating Cargo.toml features..."

# Check if hardware_tpm feature already exists
if grep -q 'hardware_tpm' Cargo.toml; then
    echo "  ✓ hardware_tpm feature already defined"
else
    echo "  ℹ TPM feature will be added during Cargo.toml update phase"
fi

# 5. Generate status report
echo ""
echo "📋 Phase 5: Generating TPM status report..."
REPORT_FILE="reports/tpm_migration_$(date +%Y%m%d_%H%M%S).md"
mkdir -p reports

cat > "$REPORT_FILE" << EOF
# TPM Migration Report
**Generated**: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
**TPM Type**: ${TPM_TYPE}
**TPM Available**: ${TPM_AVAILABLE}

## Detection Results

| Check | Result |
|-------|--------|
| /dev/tpm0 | $([ -c /dev/tpm0 ] && echo "✅ Present" || echo "❌ Not found") |
| /dev/tpmrm0 | $([ -c /dev/tpmrm0 ] && echo "✅ Present" || echo "❌ Not found") |
| tpm2_getcap | $(command -v tpm2_getcap &>/dev/null && echo "✅ Available" || echo "❌ Not found") |
| swtpm | $(command -v swtpm &>/dev/null && echo "✅ Available" || echo "❌ Not found") |

## PCR Slot Allocation

| Slot | Purpose | Description |
|------|---------|-------------|
| PCR[12] | SAPE | Scoring engine measurements |
| PCR[13] | FATE | Formal verification measurements |
| PCR[14] | SPINE | Polyglot spine measurements |
| PCR[15] | SOVEREIGN | Sovereign kernel measurements |

## Feature Flags

| Feature | Purpose | Status |
|---------|---------|--------|
| \`hardware_tpm\` | Enable real TPM | $(grep -q 'hardware_tpm' Cargo.toml && echo "✅ Defined" || echo "⚠️ Pending") |
| \`simulated_tpm\` | Software fallback | ✅ Default |

## Next Steps

1. $([ "$TPM_AVAILABLE" = true ] && echo "Enable hardware_tpm feature for production" || echo "Install TPM 2.0 or use software fallback")
2. Run attestation key generation
3. Configure PCR policies
EOF

echo "  ✓ Report saved to: $REPORT_FILE"

# 6. Final status
echo ""
echo "========================================================================"
if [ "$TPM_AVAILABLE" = true ]; then
    echo "✅ TPM MIGRATION COMPLETE: Hardware TPM detected and configured"
    echo "   Run: cargo build --features hardware_tpm"
else
    echo "⚠️  TPM MIGRATION PARTIAL: Using software fallback"
    echo "   For production: Install TPM 2.0 hardware"
fi
